// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbperycChIWYrYUD1u_Tsqm9k8iE5E2k',
    appId: '1:92912528142:web:c7480c251b775042bf855f',
    messagingSenderId: '92912528142',
    projectId: 'e-studio-b20cf',
    authDomain: 'e-studio-b20cf.firebaseapp.com',
    databaseURL: 'https://e-studio-b20cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-studio-b20cf.appspot.com',
    measurementId: 'G-FEZ5QG0WV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpEbhTO7CeO8HHN2ajMBaeomK70mOMx70',
    appId: '1:92912528142:android:5a00df60f0aadf0bbf855f',
    messagingSenderId: '92912528142',
    projectId: 'e-studio-b20cf',
    databaseURL: 'https://e-studio-b20cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-studio-b20cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGpEpnnzuWwbJAHXZjMIHgK7tCPPQvGA',
    appId: '1:92912528142:ios:bccb9e2c336727a0bf855f',
    messagingSenderId: '92912528142',
    projectId: 'e-studio-b20cf',
    databaseURL: 'https://e-studio-b20cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-studio-b20cf.appspot.com',
    iosBundleId: 'com.example.eStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGpEpnnzuWwbJAHXZjMIHgK7tCPPQvGA',
    appId: '1:92912528142:ios:bccb9e2c336727a0bf855f',
    messagingSenderId: '92912528142',
    projectId: 'e-studio-b20cf',
    databaseURL: 'https://e-studio-b20cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-studio-b20cf.appspot.com',
    iosBundleId: 'com.example.eStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtbperycChIWYrYUD1u_Tsqm9k8iE5E2k',
    appId: '1:92912528142:web:283aa1906a152e27bf855f',
    messagingSenderId: '92912528142',
    projectId: 'e-studio-b20cf',
    authDomain: 'e-studio-b20cf.firebaseapp.com',
    databaseURL: 'https://e-studio-b20cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-studio-b20cf.appspot.com',
    measurementId: 'G-YH4DHCB9CX',
  );
}
